-- Add PENDING_ADMIN_REVIEW to DocumentStatus enum
ALTER TABLE `documents` MODIFY COLUMN `document_status` ENUM(
  'SUBMITTED','ANALYSIS_IN_PROGRESS','ANALYSIS_COMPLETE','CLEAN',
  'FLAGGED_PLAGIARISM','ANALYSIS_PENDING','APPROVED','APPROVED_WITH_MENTION',
  'CONDITIONAL_APPROVAL','REQUESTED_REVIEW','REJECTED','PENDING_ADMIN_REVIEW'
) NOT NULL DEFAULT 'SUBMITTED';

-- Add staging_metadata column
ALTER TABLE `documents` ADD COLUMN `staging_metadata` JSON NULL;
